# =============================================================
# Application properties
#
# pattern.timestamp-time=yyyy-MM-dd HH:mm:ss

# =============================================================
# JPA
#
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  properties:
    hibernate:
      enable_lazy_load_no_trans: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

server:
    port: 8080
    session:
      cookie:
        name: UISESSION

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://portal.sdi4apps.eu/view
      userAuthorizationUri: http://portal.sdi4apps.eu/sso-portlet/service/sso/validate/{sessionId}
    resource:
      userInfoUri: http://portal.sdi4apps.eu/auth/user/me

#spring.jpa.database=POSTGRESQL
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#
#spring.datasource.platform=postgres
#spring.datasource.driverClassName=org.postgresql.Driver
## LOCAL TESTING
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres

# =============================================================
# Tomcat server port
#
#server.port=8080