# =============================================================
# Application properties
#
enum:
  alert:
    event: FIRST_ENUM

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
#security:
#  ignored: /**
# =============================================================
# SPRING
#
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432
    username: postgres
    password: postgres
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# =============================================================
# SERVER
#
server:
    port: 8080
    session:
      cookie:
        unitDesc: UISESSION
