# =============================================================
# Application properties
#
enum:
  alert:
    event: FIRST_ENUM
# =============================================================
# SPRING
#
spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# =============================================================
# SERVER
#
server:
    port: 8080
    session:
      cookie:
        unitDesc: UISESSION

#spring.jpa.database=POSTGRESQL
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
#
#spring.datasource.platform=postgres
#spring.datasource.driverClassName=org.postgresql.Driver
## LOCAL TESTING
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=postgres

# =============================================================
# Tomcat server port
#
#server.port=8080